### ISSUE TITLE
Incorrect genome size estimation

### ISSUE THREAD

**Issue by nirvana693** [fanagislab/kmerfreq#8]
Hi Team,

the tool is very simple to use. thank you!

I tried to test the tool on one of the sars (SRR19645658 -- Illumina) dataset to check using a k-mer size of 17 and followed by the genome size estimation using GCE as per the instructions in the GIT page. The results are super wired. the estimated genome size is around 70kb when -g option is not mentioned. If -g is mentioned as per the guidelines, the estimated genome size is 1.71568e+06!!

Any comment/inputs on these observation is appreciated.

**Comment by fanagislab** [comment]
To find the problem, I suggest that you should see the K-mer distribution curve.  There should be a clear peak of possion distribution which is caused by the random sampling of the reads.   If there is not peak, or the K-mer frequency distribtion is too strange,  the estimation result of GCE is not reliable.   It shows that the seqeuncing data has severe problem, and can't be applied for genome size estimation.





***@***.***
 
From: nirvana693
Date: 2022-06-15 11:25
To: fanagislab/kmerfreq
CC: Subscribed
Subject: [fanagislab/kmerfreq] Incorrect genome size estimation (Issue #8)
Hi Team,
the tool is very simple to use. thank you!
I tried to test the tool on one of the sars (SRR19645658 -- Illumina) dataset to check using a k-mer size of 17 and followed by the genome size estimation using GCE as per the instructions in the GIT page. The results are super wired. the estimated genome size is around 70kb when -g option is not mentioned. If -g is mentioned as per the guidelines, the estimated genome size is 1.71568e+06!!
Any comment/inputs on these observation is appreciated.

**Comment by nirvana693** [comment]
there are no clear peak except the initial frequency. Are you suggesting the tool can not be used for viral dataset? 

the dataset is very small (SRR19645658 -- Illumina), you may quickly check.  

the results are same for both TGS (I used hifi and ONT) and Illumina reads.

**Comment by fanagislab** [comment]
I think not suitable for viral.   GCE is developed for large plant and animal genomes.  The kmer frequency has large variation.  For such a small genome like virus,  the K-mer frequency based estimation of genome size is not reliable.  You may directly assembly the reads data, and see how long the contig is，   the total contig size is more accurate for the genome size estimation.






***@***.***
 
From: nirvana693
Date: 2022-06-15 16:02
To: fanagislab/kmerfreq
CC: fanwei; Comment
Subject: Re: [fanagislab/kmerfreq] Incorrect genome size estimation (Issue #8)
there are no clear peak except the initial frequency. Are you suggesting the tool can be used for viral dataset?
the dataset is very small (SRR19645658 -- Illumina), you may quickly check.
